$mod = SUPER
$terminal = foot

monitor = eDP-1, 2560x1440@60, 0x0, 1

env = AQ_DRM_DEVICES,/dev/dri/card0
env = AQ_NO_MODIFIERS,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_THEME,Bibata-Modern-Classic

xwayland {
    enabled = false
}

cursor {
    no_hardware_cursors = 1
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    resize_on_border = true
    layout = dwindle
}

decoration {
    rounding = 0
}

animations {
    enabled = false
}

misc {
    force_default_wallpaper = 0
}

debug {
    disable_logs = false
}

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        tap-to-click = true
        natural_scroll = false
    }
}

bind = $mod, Return, exec, $terminal
bind = $mod, M, exit,
bind = $mod SHIFT, E, exit,
