# BEGIN_KITTY_THEME
# Argonaut
include current-theme.conf
# END_KITTY_THEME

# Font
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.5

# Symbol fallbacks
symbol_map U+E000-U+F8FF Symbols Nerd Font
symbol_map U+F000-U+F8FF Symbols Nerd Font
symbol_map U+F0000-U+FFFFD Symbols Nerd Font
symbol_map U+100000-U+10FFFD Symbols Nerd Font

# Shell
shell /bin/zsh

# Window padding
window_padding_width 12

# Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Transparency / blur
background_opacity 0.3
dynamic_background_opacity yes

# Tabs
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{title}"

# Window decorations
hide_window_decorations no

# Scrollback
scrollback_lines 10000

# Mouse
copy_on_select yes
mouse_map right press ungrabbed paste_from_clipboard

# Bell
enable_audio_bell no
visual_bell_duration 0.0

default_pointer_shape arrow
pointer_shape_when_grabbed arrow
pointer_shape_when_dragging arrow arrow